name: paso_a_paso
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  geolocator: ^10.0.0
  flutter_map: ^6.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
